[package]
name = "hello-wasm"
version = "0.1.0"
author = ["Jungyoon Lim"]
description = "hi wasm garden"
license = "MIT"
repository = "https://github.com/Jungyoonlim/garden"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"